import { Footer } from "@/shared/components/layout/Footer/Footer";
import { Header } from "@/shared/components/layout/Header/Header";
import { Page } from "@/shared/components/ui/containers/Page/Page";
import { fonts } from "@/shared/lib/fonts";
import "@/shared/styles/globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={fonts}>
        <Page>
          <Header />
          <main>{children}</main>
          <Footer />
        </Page>
      </body>
    </html>
  );
}
