import { Page } from "@/shared/components/containers/Page/Page";
import { Footer } from "@/shared/layout/Footer/Footer";
import { fonts } from "@/shared/lib/fonts";
import "@/shared/styles/globals.css";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fonts}>
        <Page>
          <main>{children}</main>
          <Footer />
        </Page>
      </body>
    </html>
  );
}
